2017-11-02 11:43:30,249 [8268] INFO  FormLogin - ****************************异常文本****************************
【出现时间】：2017-11-02 11:43:30
【异常类型】：DivideByZeroException
【异常信息】：尝试除以零。
【堆栈调用】：   在 System.Decimal.FCallDivide(Decimal& d1, Decimal& d2)
   在 System.Decimal.op_Division(Decimal d1, Decimal d2)
   在 POS.Helper.CalcMoneyHelper.Divide(Object obj1, Object obj2) 位置 D:\开发\开发\Pos\POS\Helper\CalcMoneyHelper.cs:行号 153
   在 POS.Sale.FormMain.AddPos(GoodModel good) 位置 D:\开发\开发\Pos\POS\Sale\FormMain.cs:行号 915
   在 POS.Sale.FormMain.SearchProduct() 位置 D:\开发\开发\Pos\POS\Sale\FormMain.cs:行号 514
   在 POS.Sale.FormMain.bteProduct_KeyDown(Object sender, KeyEventArgs e) 位置 D:\开发\开发\Pos\POS\Sale\FormMain.cs:行号 494
   在 System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   在 DevExpress.XtraEditors.BaseEdit.OnKeyDown(KeyEventArgs e)
   在 System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   在 DevExpress.XtraEditors.Mask.MaskBox.OnKeyDown(KeyEventArgs e)
   在 System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   在 System.Windows.Forms.Control.WmKeyChar(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.TextBox.WndProc(Message& m)
   在 DevExpress.XtraEditors.Mask.MaskBox.WndProc(Message& m)
   在 DevExpress.XtraEditors.TextBoxMaskBox.WndProc(Message& msg)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
***************************************************************

2017-11-02 14:38:42,451 [9360] INFO  FormLogin - ****************************异常文本****************************
【出现时间】：2017-11-02 14:38:42
【异常类型】：IndexOutOfRangeException
【异常信息】：索引超出了数组界限。
【堆栈调用】：   在 POS.Sale.FormMain.QueryClnt() 位置 D:\开发\开发\Pos\POS\Sale\FormMain.cs:行号 617
   在 POS.Sale.FormMain.bteClientCode_KeyDown(Object sender, KeyEventArgs e) 位置 D:\开发\开发\Pos\POS\Sale\FormMain.cs:行号 593
   在 System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   在 DevExpress.XtraEditors.BaseEdit.OnKeyDown(KeyEventArgs e)
   在 System.Windows.Forms.Control.OnKeyDown(KeyEventArgs e)
   在 DevExpress.XtraEditors.Mask.MaskBox.OnKeyDown(KeyEventArgs e)
   在 System.Windows.Forms.Control.ProcessKeyEventArgs(Message& m)
   在 System.Windows.Forms.Control.WmKeyChar(Message& m)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.TextBox.WndProc(Message& m)
   在 DevExpress.XtraEditors.Mask.MaskBox.WndProc(Message& m)
   在 DevExpress.XtraEditors.TextBoxMaskBox.WndProc(Message& msg)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
***************************************************************

2017-11-02 15:53:37,751 [9436] INFO  FormLogin - ****************************异常文本****************************
【出现时间】：2017-11-02 15:53:32
【异常类型】：WebException
【异常信息】：无法连接到远程服务器
【堆栈调用】：   在 POS.Common.utility.HttpClient.AsyncCallback[T](IAsyncResult ar) 位置 D:\开发\开发\Pos\POS.Common\utility\HttpClient.cs:行号 178
   在 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   在 System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   在 System.Net.HttpWebRequest.SetResponse(Exception E)
   在 System.Net.ConnectionReturnResult.SetResponses(ConnectionReturnResult returnResult)
   在 System.Net.Connection.CompleteConnectionWrapper(Object request, Object state)
   在 System.Net.PooledStream.ConnectionCallback(Object owningObject, Exception e, Socket socket, IPAddress address)
   在 System.Net.ServicePoint.ConnectSocketCallback(IAsyncResult asyncResult)
   在 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   在 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   在 System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   在 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
***************************************************************

2017-11-02 15:53:37,765 [8316] INFO  FormLogin - ****************************异常文本****************************
【出现时间】：2017-11-02 15:53:32
【异常类型】：WebException
【异常信息】：无法连接到远程服务器
【堆栈调用】：   在 POS.Common.utility.HttpClient.AsyncCallback[T](IAsyncResult ar) 位置 D:\开发\开发\Pos\POS.Common\utility\HttpClient.cs:行号 178
   在 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   在 System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   在 System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   在 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   在 System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   在 System.Net.HttpWebRequest.SetResponse(Exception E)
   在 System.Net.ConnectionReturnResult.SetResponses(ConnectionReturnResult returnResult)
   在 System.Net.Connection.CompleteConnectionWrapper(Object request, Object state)
   在 System.Net.PooledStream.ConnectionCallback(Object owningObject, Exception e, Socket socket, IPAddress address)
   在 System.Net.ServicePoint.ConnectSocketCallback(IAsyncResult asyncResult)
   在 System.Net.LazyAsyncResult.Complete(IntPtr userToken)
   在 System.Net.ContextAwareResult.Complete(IntPtr userToken)
   在 System.Net.LazyAsyncResult.ProtectedInvokeCallback(Object result, IntPtr userToken)
   在 System.Net.Sockets.BaseOverlappedAsyncResult.CompletionPortCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* nativeOverlapped)
   在 System.Threading._IOCompletionCallback.PerformIOCompletionCallback(UInt32 errorCode, UInt32 numBytes, NativeOverlapped* pOVERLAP)
***************************************************************

